# np.result_type(Object_name)
### for checking the data type of a particular object.

In [ ]:
import numpy as np
lst = [10, 20, 30, 40] 
arr = np.array(lst,)
print(arr)
# [2 5 6 8]
print(type(arr))
# class 'numpy.ndarray'
print(np.result_type(arr))
# int32  ,

# arange(from, to, interval, datatype) 
#### gives uncertain number of values based on steps
# linspace(from, to, no_of_values , datatype)
#### Hence, we use linspace, which asks for total number of values


In [11]:

''' Creation of an array with step size 1.33 between 0 - 10 '''
arr2 = np.arange(0, 10, 1.33, dtype = np.float64)
print(arr2)
print(type(arr2))
print(np.result_type(arr2))
# [0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
# <class 'numpy.ndarray'>
# float64

'''Creation of an array with total 5 values from 0-160'''
print(np.linspace(0, 160, 5, dtype = np.float64))
#[  0.  40.  80. 120. 160.]

[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
<class 'numpy.ndarray'>
float64
[  0.  40.  80. 120. 160.]


# Generating Matrices in NumPy

In [ ]:
''' Method I: Using array and reshape to convert array into matrix '''
print(np.array([5,6,8,45,12,52]).reshape(3,2),"\n")
print(np.array([2,3,4,5,6,7,8,9,0,1]).reshape(2,5),"\n\n") #My example
# [[ 5  6  8]
#  [45 12 52]]


''' Method II: Using matrix function '''
print(np.matrix([[1,2],
                [3,4]]),"\n")

print(np.matrix([[1,1,1],[2,2,2],[3,3,3]]),"\n\n")  #my example
# [[1 2]
#  [3 4]]


''' Method III: Using misc. functions '''
print(np.eye(3),"\n") # Identity matrix
print(np.eye(4),"\n\n") #my example

print( np.zeros( (4,3) ),"\n" )
print( np.zeros( (4,4)), "\n\n") #my example

print(np.ones( (3,3), dtype = np.float64 ),"\n")
matrix1 = np.ones( (4,4)) # my example no dtype is asigned ....
print(matrix1,"\n",np.result_type(matrix1))


Problem Statement:
Given two NumPy arrays arr1 = [25, 56, 12, 85, 34, 75] and arr2 = [42, 3, 86, 32, 856, 46], solve the following:

Create a new NumPy array Narr with the shape equal to arr1 filled with random values.

Permanently change the dtype of arr1 to complex.

Transform arrays arr1 and arr2 into two matrices (arr1_mat and arr2_mat) of shape (2,3) and arrive at the solution of the following equation: [(arr1_mat)^2 - (arr2_mat)^2] / [(arr1_mat)-(arr2_mat)]



### numpy.square() - used to square a value/list/array
### numpy.random.rand() - used to generate random no.
### complex (x) for x in list - used to typecast array into complexNo.
### astype() - to typecast an array to another datatype

In [ ]:
import numpy as np
arr1 = np.array([25, 56, 12, 85, 34, 75])
arr2 = np.array([42, 3, 86, 32, 856, 46])

Narr = np.linspace(np.random.rand(),np.random.rand(),6,dtype= np.float32)
arr1 = arr1.astype(complex)

arr1_mat = np.array(arr1).reshape(2,3)
arr2_mat = np.array(arr2).reshape(2,3)

print(Narr,"\n",arr1,"\n",np.result_type(arr1)) #checking if the values have changed 
print("\n",arr1_mat,"\n",arr2_mat,"\n\n") #checking the matrix conversion

solution = (np.square(arr1_mat) - np.square(arr2_mat)) / (arr1_mat - arr2_mat)

print("Solution : ", solution)

In [ ]:
#Example of arr.reshape(4,-1) function and arr.shape() function
import numpy as np
arr = np.arange(4).reshape(4,-1)
print(arr,"\n",arr.shape)

## numpy.less(to_campare , with )

## Vectorized operations
Suppose we're given a literacy rate data sample of State X and State Y for two consecutive years measured quarterly on a scale of 0-10. Let us try to arrive at the following outcomes:

Quarterly difference between each state's literacy rate per year.

Quarters having a literacy rate less than 2.

Find out the cumulative sum of literacy rates by the end of every quarter each year. Find out the quarters for which this sum is greater or equal to 8.  

Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.

The data for each state is given below: as S_X and S_Y

In [5]:
import numpy as np
S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
# [[2 5 6 5]
#  [4 8 6 5]]


S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y , "\n")
# [[6 7 5 9]
#  [7 5 6 4]] 

print(S_X - S_Y, "\n\n") #1. Quarterly difference between each state's literacy rate per year

print(S_X < 2) #2. Quarters having a literacy rate less than 2
twos_mat = np.ones((2, 4)) * 2 # method 2 by creating a 2's matrice and comparison by numpy.less()
print(np.less(S_Y, twos_mat), "\n\n")

#Find out the cumulative sum of literacy 
# rates by the end of every quarter each year. 
# Find out the quarters for which this sum 
# is greater or equal to 8.
eights_mat = np.ones((1,4)) * 8 
print(S_X[0] + S_X[1])
print((S_X[0] + S_X[1]) >= eights_mat)
print(S_Y[0] + S_Y[1])
print((S_Y[0] + S_Y[1]) >= eights_mat,"\n\n")

#Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.
mean_X = sum(S_X[0])/len(S_X[0]) , sum(S_X[1])/len(S_X[1])
mean_Y = (S_Y[0]+S_Y[1])/len(S_Y)
print(mean_X)
print(mean_Y)

[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]] 

[[-4 -2  1 -4]
 [-3  3  0  1]] 


[[False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]] 


[ 6 13 12 10]
[[False  True  True  True]]
[13 12 11 13]
[[ True  True  True  True]] 


(4.5, 5.75)
[6.5 6.  5.5 6.5]


ProblemStatement:
Solve the following:
Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.

In [20]:
import numpy as np
arr = np.eye(4)
arr[0][1] = 4
arr[1][2] = 5
arr[2][3] = 6
s = np.arange(len(arr))
arr[s[1:],s[:-1]] = [3, 2, 1] #done for extra practice
print(s)
print(arr,"\n\n\n")
                    

                    
a = np.arange(25).reshape(5,5)
s = np.arange(len(a))
a[[0,1, 2, 3] ,[1, 2, 3, 4]] = [10,20,30,40]

print(s)
print(s[:-1], s[1:],"\n")
print(a)


[0 1 2 3]
[[1. 4. 0. 0.]
 [3. 1. 5. 0.]
 [0. 2. 1. 6.]
 [0. 0. 1. 1.]] 



[0 1 2 3 4]
[0 1 2 3] [1 2 3 4] 

[[ 0 10  2  3  4]
 [ 5  6 20  8  9]
 [10 11 12 30 14]
 [15 16 17 18 40]
 [20 21 22 23 24]]


Given a Numpy array arr = np.arange(11), negate all the elements between 6 and 10.

In [ ]:
import numpy as np
arr = np.arange(11)
arr[7:10]= -arr[7:10]
print(arr)

Given a matrix mat and an array arr, for each row of the matrix if elements of Column 1 are equal to the corresponding element of the array, then print the corresponding value of Column 2 of the matrix.

In [ ]:
import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 
print(mat)
print(arr)
# print(mat[0][1])
# print(len(mat))
for i in range(4) :
    if mat[i][0] == arr[i]: 
        print(mat[i][1])


Given a matrix mat, sort it by the second column.
#### here np.argsort(matrix_name[column]) is used to sort 

In [ ]:
import numpy as np
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
#print(mat[:,1]) used to print 2nd column
print(mat[np.argsort(mat[:,1])])

Given an array arr, find the top 4 maximum values.
##### array_name.argsort() returns the sorted array

In [2]:
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
arr.sort()
print(arr,arr[-4:]) #printing last 4 elements arr[-4:]

[  0  13  13  14  16  24  45  50  90 590] [ 45  50  90 590]


Find the nearest number from the given number in an array.
##### array_name.argmin() -returns the index of the minimum value in the given array.

In [3]:
import numpy as np
arr = np.array([10,55,22,3,6,44,9,53,54])
nearest_to = 50
idx = (np.abs(arr-nearest_to)).argmin() # stores index of the minimum in the calculated distance array.
print(arr[idx],",",idx)


53 , 7


Additional operations
Q.Find out the cumulative sum of literacy rates by the end of every quarter each year. Find out the   quarters for which this sum is greater or equal to 8.  

In [8]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
# [[ 2  7 13 18]
#  [ 4 12 18 23]]
print( X_cumsum >= 8)
# [[False False  True  True]
#  [False  True  True  True]]
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
# [[ 6 13 18 27]
#  [ 7 12 18 22]]
print( Y_cumsum >= 8)
# [[False  True  True  True]
#  [False  True  True  True]] 

[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.

In [9]:
 
print(np.mean(S_X, axis = 1))
# [ 4.5   5.75]

[4.5  5.75]


To find mean of quarterly literacy rate for State Y, we find mean with axis = 0.

In [10]:
 
print(np.mean(S_Y, axis = 0))
# [ 6.5  6.   5.5  6.5]
 

[6.5 6.  5.5 6.5]


In [19]:
import numpy as np
arr1 = np.arange(5)
print(arr1[0])
arr2 = arr1 
arr2[0]+= 25
print(arr1[0])
print(arr2[0])

0
25
25
